name: Meu primeiro fluxo de trabalho
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  test:
    runs-on: windows-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Run tests
         run: |
           echo "Running tests..."
            # Aqui você pode adicionar comandos para rodar seus testes, por exemplo:
            # dotnet test MyProject.Tests/MyProject.Tests.csproj
